# install with pre-commit install

default_install_hook_types:
  - commit-msg
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: needs-prefix
        name: commit message needs to have a prefix
        language: pygrep
        entry: '^(chore|ci|junk|test|feat|fix|build|docs|refactor)!?(\([a-z]+\))?: (?![A-Z])(?![a-z]+(ed|ing)\s).*$'
        args:
          - '--multiline'
          - '--negate'
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.0.1
    hooks:
      - id: pyrefly-typecheck-specific-version
        name: Pyrefly
        pass_filenames: false
        additional_dependencies: ["pyrefly==0.37.0"]
        args: ["--ignore", "import-error"]
